### ISSUE TITLE
Add `schemas` folder to `.gitignore`

### ISSUE THREAD

**Issue by CyraLX** [SnaveSutit/origins-mod-vscode-extension#39]
I noticed after forking this repo then when I build it using `yarn build` it changes a ton of stuff in `schemas` folder to what I can assume is version/os differences. I use Linux and it's producing different results.

Adding `schemas` folder to be ignored by github in `.gitignore` prevents the need to commit and push unnecessary `.json` files which are generated on using `yarn build` thus it's unnecessary to include in the repo and fixes the version/os differences.

Unless there is something else I didn't take into account you already have which is very likely.

**Comment by CyraLX** [comment]
![image](https://user-images.githubusercontent.com/51757300/223454678-e523849d-dc83-42cf-bfce-c26029524d19.png)
Example of what I meant

**Comment by SnaveSutit** [comment]
Unfortunately I can't `.gitignore` that folder since it needs to be included in the built extension, and the extension's compiler takes the `.gitignore` into account when building.

The solution I can put into place is path normalization, just making sure all paths are forward slashes instead of double backslash.

**Comment by SnaveSutit** [comment]
Should be fixed in the latest push
