### ISSUE TITLE
[BUG] A few potential bugs (or my skill issues)

### ISSUE THREAD

**Issue by ThDilos** [SnaveSutit/origins-mod-vscode-extension#53]
**Describe the bug**
1. Entity Condition "[origins:gamemode](https://origins.readthedocs.io/en/latest/types/entity_condition_types/gamemode/)" does not show suggestions in the field "gamemode"
2. Damage Condition "[origins:name](https://origins.readthedocs.io/en/latest/types/damage_condition_types/name/)" has a wrong set of suggestions in the field "name", it appears to use the suggestions for the field "damage_type" from Damage Condition "origins:type", which cannot be used. The correct list [here](https://origins.readthedocs.io/en/latest/misc/extras/damage_source_names/). And it's mad about me using the correct one :(
3. Entity Condition "[origins:inventory](https://origins.readthedocs.io/en/latest/types/entity_condition_types/inventory/#inventory)" does not have a hyperlink attached to its introduction when mouse hovering
4. "type" in [Recipe Datatype](https://origins.readthedocs.io/en/latest/types/data_types/crafting_recipe/) is using origins/apoli as prefix, which cannot be used and should be minecraft instead.

**Potential Skill Issues**:
5. I cannot use this plugin without a VPN :(
It shows unable to load schema
This didn't happen before Plugin Version 2.2.0
My guess is my ISP banned certain types of connection
6. When you have too many certain stuff (idk what the stuff is, either keyword "type" or curly brackets or others) inside a square bracket, the plugin stopped showing suggestion and quickfills completely. There is a certain limit. Attached file marked the limit (at least in my machine).

**To Reproduce**
As explained above

**Expected behavior**
1. Show suggestions for field "gamemode".
2. Correct "name" field suggestion and error marking
3. Attach a hyperlink to the description
4. Correct recipe datatype
5. idk, ig I just continue using VPN if unfixable
6. No Limit..?

**Screenshots**
![No Gamemode Suggestion](https://github.com/user-attachments/assets/b0ba7b42-1ea8-4107-8941-aa16c684b076)
![Damage Condition](https://github.com/user-attachments/assets/df4cd41f-a0d7-4bbb-b14e-c6efacf54137)
![Inventory Condition](https://github.com/user-attachments/assets/875900e5-4fb2-4222-82fb-738f9808258d)
![Recipe](https://github.com/user-attachments/assets/8e5a707d-b8b8-4471-ab2e-4c878dd40f1d)
![Other cannot be used](https://github.com/user-attachments/assets/fa58a596-78b8-415f-aae1-f42b1c286666)
![Unable to load](https://github.com/user-attachments/assets/90f24134-5656-4de2-b5a3-93666efc8d63)
**Example File showing the limit**: [plugin_uplimit.json](https://github.com/user-attachments/files/16735362/plugin_uplimit.json)
**Video Demonstration**: https://github.com/user-attachments/assets/39c44de7-ed82-4b5f-b7fc-6a5c188d5d68

**Comment by SnaveSutit** [comment]
I can't do anything about the VPN requirement, as the connections are from internal VSCode code trying to grab the external JSON Schemas that provide the structures of the JSON files. 😞 

I cannot reproduce the failure to produce suggestions at the end of a long file. It may just be that VSCode is limiting it in order to not tank performance? I'm not sure.

The other issues look like oversights or mistakes, so I can take care of those in a few days.

- [x] Entity Condition "[origins:gamemode](https://origins.readthedocs.io/en/latest/types/entity_condition_types/gamemode/)" does not show suggestions in the field "gamemode"
- [x] Damage Condition "[origins:name](https://origins.readthedocs.io/en/latest/types/damage_condition_types/name/)" has a wrong set of suggestions in the field "name", it appears to use the suggestions for the field "damage_type" from Damage Condition "origins:type", which cannot be used. The correct list [here](https://origins.readthedocs.io/en/latest/misc/extras/damage_source_names/). And it's mad about me using the correct one :(
- [ ] Entity Condition "[origins:inventory](https://origins.readthedocs.io/en/latest/types/entity_condition_types/inventory/#inventory)" does not have a hyperlink attached to its introduction when mouse hovering
- [x] "type" in [Recipe Datatype](https://origins.readthedocs.io/en/latest/types/data_types/crafting_recipe/) is using origins/apoli as prefix, which cannot be used and should be minecraft instead.

**Comment by Snapshotlight** [comment]
Sadly I found that even with a VPN it is still impossible for me in China mainland to use this plugin. I'm wondering if the VPN is useable for the connections in VS Code.

**Comment by ThDilos** [comment]
> Sadly I found that even with a VPN it is still impossible for me in China mainland to use this plugin. I'm wondering if the VPN is useable for the connections in VS Code.

I use Netch, it even has a preset for VS Code
But you'd need a proxy server first :/

**Comment by SnaveSutit** [comment]
You could download this repo: https://github.com/SnaveSutit/origins-mod-json-schemas, and manually connect the JSON Schemas to your VSCode: https://code.visualstudio.com/docs/languages/json#_json-schemas-and-settings

**Comment by SnaveSutit** [comment]
I've fixed the two first issues and the last.
The third issue looks like a docs issue, so the docs will need to be updated before I can fix it.
![image](https://github.com/user-attachments/assets/dbd403f1-5bc1-4246-9615-ae016fb58c93)
I have made a separate issue for tracking it: https://github.com/SnaveSutit/origins-mod-vscode-extension/issues/56
